### ISSUE TITLE
AppState: no reactivity for second object member

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#11]
This code works:
```javascript
AppState.set('object', { a: 1, b: 1 });
Tracker.autorun(function() { console.log(AppState.get('object.a')); });
AppState.set('object', { a: 2, b: 2 });
```
Output, as expected:
```
1
2
```
This code doesn't work (change line 2: `b` instead of `a`)
```javascript
AppState.set('object', { a: 1, b: 1 });
Tracker.autorun(function() { console.log(AppState.get('object.b')); });
AppState.set('object', { a: 2, b: 2 });
```
Unexpected output:
```
1
```

**Comment by LuisHerranz** [comment]
I have created a test and it's working fine here.
https://github.com/worona/meteorflux/blob/devel/packages/appstate/tests/client/appstate-tests.js#L794

And it's working fine in the Chrome console as well:
![screen shot 2015-10-16 at 17 10 21](https://cloud.githubusercontent.com/assets/3305402/10545461/155c64dc-7429-11e5-99ff-a6fd7414cb7a.png)

Please check your code and if it still fails, create a failing test and make a pull request so I can solve it.

**Comment by steph643** [comment]
Well, if you cannot reproduce it on your side, I don't think a PR will help :-)

Can you please run this [MeteorPad](http://meteorpad.com/pad/pWSqxwGrRmkKPAXgF/AppState%20issue)? (it doesn't work on my side)

And it doesn't work in my console either:
![image](https://cloud.githubusercontent.com/assets/7039479/10546489/8d71dd26-742e-11e5-8ee7-2e335cdc20dc.png)

**Comment by steph643** [comment]
My environment: Meteor 1.2 + Windows 7 + Chrome.

**Comment by steph643** [comment]
A few more hints:
* Reactivity still doesn't fire when using `AppState.get('object.b')` from a template helper instead of `autorun`,
* **But** reactivity fires normally when using your global helpers `{{object.b}}`!

**Comment by LuisHerranz** [comment]
I meant a PR of a failing test, like this one: https://github.com/worona/meteorflux/blob/devel/packages/appstate/tests/client/appstate-tests.js#L794

I will work on it as soon as I can.
