### ISSUE TITLE
AppState: AppState.get fails when object contains an array field

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#13]
Consider the following code:
```javascript
AppState.set('object', { myArray: [] });
console.log(AppState.get('object'));
```
Expected output:
```
▼ Object {myArray: Object}
  ► myArray: Array[0]
```
Actual output (an additional 'array' field has been added):
```
▼ Object {myArray: Object}
  ▼ myArray: Object
    ► array: Array[0]
```

**Comment by LuisHerranz** [comment]
Yes, that was actually part of the implementation so you can add properties to arrays, and do stuff like:

```html
{{#if posts.isReady}}
  {{#each posts}}
    {{> post}}
  {{/each}}
{{/if}}
```

So it works with Blaze, but it looks like I forgot to output it correctly with the `AppState.get()` as well.

I have added a failing test here
https://github.com/worona/meteorflux/blob/devel/packages/appstate/tests/client/appstate-tests.js#L808
and will work on it as soon as I can.

**Comment by steph643** [comment]
@LuisHerranz, any idea about when you can work on this? Sorry for the push, but your package is so full of possibilities that I am planning to base my app on it :-)

**Comment by LuisHerranz** [comment]
I am glad you like this package and I want to thank you for your contribution here, but be aware that it is still highly experimental and we may change how it works.

**Comment by steph643** [comment]
Thanks :-)

**Comment by LuisHerranz** [comment]
Ok, this bugs comes from the implementation which made this possible:

```html
<template name='VideoPlayerList'>
  {{#if videoList.isReady}}
    {{#each videoList}}
      {{> VideoPlayer}}
    {{/each}}
  {{/if}}
</template>
```

Now this is not possible anymore, you have to use a separate property for the array, like for example `items`.
```html
<template name='VideoPlayerList'>
  {{#if videoList.isReady}}
    {{#each videoList.items}}
      {{> VideoPlayer}}
    {{/each}}
  {{/if}}
</template>
```

Less elegant but less prone to bugs.

**Comment by steph643** [comment]
Thanks for the fix.
Just so that I understand your example, what do you store in `AppState.set('videoList', ?)`?

**Comment by LuisHerranz** [comment]
You can still do
```javascript
AppState.set('VideoList', {
  items(): {
    return Videos.find();
  },
  isReady: false;
})
```
or
```javascript
AppState.set('VideoList.items', () => Videos.find());
AppState.set('VideoList.isReady', false);
```
