### ISSUE TITLE
AppState: autorun not cleaned up

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#16]
Working code:
```javascript
Session.set('value', 1);
AppState.set('a', function() {
  console.log('Function called!');
  return Session.get('value');
});
Meteor.setTimeout(function() {
  Session.set('value', 2);
}, 1000);
```
Output, as expected:
```
Function called!
Function called!
```
Non-working code:
```javascript
Session.set('value', 1);
AppState.set('a', function() {
  console.log('Function called!');
  return Session.get('value');
});
AppState.set('a', 'notAFunctionAnymore');
Meteor.setTimeout(function() {
  Session.set('value', 2);
}, 1000);
```
Unexpected output:
```
Function called!
Function called!
```

**Comment by LuisHerranz** [comment]
You shouldn't be using AppState to create random computations. Use Tracker.autorun for that and you can control when to stop them.

**Comment by steph643** [comment]
What random computation are you talking about?
If you think this issue is not worth fixing, you can call it a "limitation" and add something in the doc about it :-)

**Comment by LuisHerranz** [comment]
With random computation I mean, use function() only to retrieve a value using `return`, not to process other stuff not related to the value you are setting.

It took me a while but I have created a failing test related to this case:
https://github.com/worona/meteorflux/commit/9f351e96ab6668883345efab6ab1c3f483fb082c

**Comment by LuisHerranz** [comment]
This is quite complex with the current implementation, so I won't fix it for now until we see if this is really an issue or not.

If it is, I will bring it back.

**Comment by steph643** [comment]
Sounds reasonable. 
My initial thought was to store the computation in the `_deps` tree and to recurse through children when a `set` occurs, in order to stop any computation. But you probably thought about this already.

**Comment by steph643** [comment]
Having something in the doc about this would be nice (maybe in the *Possible improvements* paragraph), so that we don't forget about it.
