### ISSUE TITLE
AppState: better package name?

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#18]
An "app state" is a kind of data. But since this package allows to store any kind of data, I think it would better be called `ReactiveObj`. This would be consistent with core packages `ReactiveVar` and `ReactiveDict`.

**Comment by LuisHerranz** [comment]
There is already other project called `ReactiveObj`. Besides, those packages are not singletons and AppState is (or that's the main purpose). I would leave that naming to classes/prototypes to create new reactive variables.

https://github.com/xamfoo/reactive-obj

**Comment by steph643** [comment]
IMO, the singleton should be in a different package.
Ideally, there would be a `Session2` package with the singleton (with a Session2 singleton that you can use to store the app state if you want), relying on a `ReactiveObj` package providing the reactive object. This would be the same scheme as core packages `Session` and `ReactiveDict`, and thus immediately understandable by people.

**Comment by LuisHerranz** [comment]
Seems reasonable. We'll think about it.

**Comment by LuisHerranz** [comment]
We are testing AppState without `set`, only with `modify`, so I will probably create this other package with the actual AppState.

What do you think of the name: `ReactiveData`?

Then AppState would become the singleton integrated with the Flux Dispatcher for "redux" kind of apps.

**Comment by steph643** [comment]
`ReactiveData` is ok, although a bit generic. Another idea: `ReactiveVar2`.

**Comment by steph643** [comment]
Speaking about xamfoo:reactive-obj, what do you think about it? Maybe your doc should have a line of explanation about the differences with this other package?

**Comment by LuisHerranz** [comment]
ReactiveObj is great. First version of AppState was built on top of it.

The final name for the package is going to be `ReactiveState`.
