### ISSUE TITLE
ReactiveState: support non-plain object

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#20]
Working code:
```javascript
AppState.set('object', { field: 33 });
console.log(AppState.get('object'));
console.log(AppState.get('object.field'));
```
Output, as expected:
```
Object {field: 33}
33
```
Non-working code:
```javascript
function MyObject() { this.field =  33; }
AppState.set('object', new MyObject);
console.log(AppState.get('object'));
console.log(AppState.get('object.field'));
```
Unexpected output:
```
Object {field: 33}
undefined
```

**Comment by steph643** [comment]
This "non-plain object" thing causes issues with `get`, but also with reactivity (changes on the field won't trigger reactivity).

**Comment by LuisHerranz** [comment]
Hi @steph643,

**AppState** is an object tree to save the state of your application. It is not intended to be used to store complex objects or classes/prototypes. Support for Functions are there mostly to support Mongo Cursors.

Could you please share an example where you need to store this type of object in the state of your app?

**Comment by steph643** [comment]
The issue is that many meteorites use the [collection-helpers](https://github.com/dburles/meteor-collection-helpers) package, which turns any collection document into a non-plain object. 

For example, here is what I get in my app:
```javascript
console.log(Meteor.user());
```
![image](https://cloud.githubusercontent.com/assets/7039479/10697121/9534f634-79aa-11e5-9cc4-b72f34fda047.png)

What I wish I could do with AppState is simply this:
```javascript
const handle = Meteor.subscribe('currentUser');
AppState.set('user', function() {
  if (!handle.ready())
    return undefined;
  return Meteor.user() || { _id: null };
});
```

**Comment by LuisHerranz** [comment]
Hmm... I've just tried this:
```javascript
AppState.set('user', function() {
  return Meteor.user();
});
```
and it works fine. It returns:
```json
{
  "_id": "DpqQo9BKgy4y3vwh7",
  "emails": [
    {
      "address": "b@b.com",
      "verified": false
    }
  ],
  "firstName": "John"
}
```
`AppState.get('user.firstName')`  returns `"John"` and `AppState.get('user.emails')` returns the correct array.

Which one is not working?

**Comment by steph643** [comment]
I think it works because your `Meteor.user()` returns a plain object, whereas mine returns a non-plain object because of `collection-helpers`.

**Comment by LuisHerranz** [comment]
I see.

Is there any other example which triggers this behaviour, but with some part of Meteor's core and not an external package?

**Comment by steph643** [comment]
I can't think of any other example.
I am not sure this issue is a big deal, as it is probably possible to convert data to plain objects before storing (I will do some tests tomorrow).
However, I think it is important to display a warning or to trigger an exception when a non-plain object is provided, because it causes bugs difficult to catch (especially with reactivity).

**Comment by LuisHerranz** [comment]
I will update the docs :+1:

**Comment by steph643** [comment]
And please though an exception. Many people don't realize they got non-plain objects everywhere because of `collection-helpers`.

**Comment by LuisHerranz** [comment]
Ok.

**Comment by luisherranz** [comment]
@steph643 ReactiveState now can storage complex objects. Could you please give it a try and let me know if it works?

**Comment by luisherranz** [comment]
It looks like it's working fine so far so I am going to close this now. Reopen it if you find any issue.
