### ISSUE TITLE
Order of fields somehow matters - getMeteorData not triggered

### ISSUE THREAD

**Issue by ffxsam** [worona/meteorflux#21]
I just discovered something odd. When I set my state like this:

    AppState.set('artistTrack', {
      activeTrackId: action.trackId,
      audioPlayer: {
        command: 'play',
        url: action.url
      }
    });

My component that references `AppState.get('artistTrack.audioPlayer')` in `getMeteorData` does not fire off. But when I change the order of the above to:

    AppState.set('artistTrack', {
      audioPlayer: {
        command: 'play',
        url: action.url
      },
      activeTrackId: action.trackId
    });

Then it works as expected.

**Comment by LuisHerranz** [comment]
Hi Sam,

Have you updated to v1.1.1?

**Comment by ffxsam** [comment]
Aha! That did it. :) Thank you!
