### ISSUE TITLE
Major breaking changes?

### ISSUE THREAD

**Issue by ffxsam** [worona/meteorflux#24]
I noticed `AppState.set` is gone, so I've had to update my project to use `AppState.modify` and change the patterns a bit. Just wondering why the option to use `set`/Flux was removed entirely.

**Comment by LuisHerranz** [comment]
We are experimenting with **AppState** a lot so for those of you using it with the `get` and `set` methods, we created a new package called `ReactiveState`.
https://github.com/worona/meteorflux/tree/devel/packages/reactive-state

It has the same functionality of the old AppState and it is stable.

It's not a singleton, so you have to do something like this:
```javascript
AppState = new ReactiveState();
```
probably in the client/lib folder so it's loaded before anything else.
