### ISSUE TITLE
FTF and asynchronous state change

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#26]
Does this work?:
```javascript
let text = '';

First(() => {
  switch (Action.type()) {
    case 'SOMETHING_HAPPENED_1':
      text = text + 'First, ';
      break;
    case 'SOMETHING_HAPPENED_2':
      break;
  }
});

Then(() => {
  if (Action.is('SOMETHING_HAPPENED_1')) {
    const subHandle = Meteor.subscribe('posts');
    State.set('something', function() {
      return subHandle.ready();
    });
  }
});

Then(() => {
  if (Action.is('SOMETHING_HAPPENED_1') && (State.get('something') === true))
    text = text + 'Then, ';
});

Finally(() => {
  if (Action.is('SOMETHING_HAPPENED_1'))
    text = text + 'Finally!';
    console.log(text);
});

Dispatch('SOMETHING_HAPPENED_1');
Dispatch('SOMETHING_HAPPENED_2');

// it should print:
// => 'First, Then, Finally!'
```
If it doesn't, how would you implement this behavior with FTF?

**Comment by steph643** [comment]
Some thoughts:
 * I don't think "something" should be considered part of the application state. It is rather an *action* state, a temporary state used until the action has been completely processed.
 * Implicit autorun creation - which is what you do in "Then" - should be avoided if possible. It is what has killed Iron Router, the most established Meteor package.

Hence this proposal:
```javascript
Dispatcher.register('SOMETHING_HAPPENED_1', function(action){
  const subHandle = Meteor.subscribe('posts');
  this.set('something', function() {             // Store data in the action state
    return subHandle.ready();
  });
  action.done();
});

Dispatcher.register('SOMETHING_HAPPENED_1', function(action){
  this.autorun({
    if (! this.get('something'))
      return;
    text = text + 'Then, ';
    this.done();   // Kills all autoruns and allow next action to be processed
  });
});
```
A global callback might be possible by replacing this.set/this.get/this.done by action.get/action.set/action.done.

**Comment by LuisHerranz** [comment]
@steph643 thanks for keeping up with us, testing and trying these packages.

There are problems with Action-driven (Flux) and Data-drivern (Meteor) approaches when working in real world scenarios. They can be solved if you are in control of all your code (non-extensible app) but not in extensible apps where some developers don't have access to change the core.

We are still working on this idea. It has turned very intuitive and useful, but we are not happy with the API.

> I don't think "something" should be considered part of the application state. It is rather an action state, a temporary state used until the action has been completely processed.

That was just an example, probably not the best example in the world.

> Implicit autorun creation - which is what you do in "Then" - should be avoided if possible. It is what has killed Iron Router, the most established Meteor package.

We are no using `Then` functions actually, so we may remove them, yes. What we are using in that step are just `State.modify` redux type of functions but with **Reactive Actions** (which is the important change here).

So we are probably back to `Dispatcher.register()` and `State.modify()` but with a reactive `Action.type()` for the state modification and substitute `Finally` for something like `Dispatcher.afterAction()` for those special cases when it's needed.

In the end, I hope to make it so simple you wouldn't have to think any of this. It'll just make sense and work.

**Comment by steph643** [comment]
This is really interesting. I look forward to seeing your next API.

**Comment by luisherranz** [comment]
You can take a look at the new API here:
https://github.com/worona/meteorflux/

We have been using it for a while and we are happy with it so we don't see any upcoming changes in the near future. I will close this now.
