### ISSUE TITLE
Property 'First' of object [object Object] is not a function

### ISSUE THREAD

**Issue by jaskinn** [worona/meteorflux#27]
Trying to create a minimal project. I know I'm doing something wrong, but I'm stumped.

>meteor create test
> cd test
> meteor add meteorflux:first-then-finally

append to test.js

"First(()=>{console.log('test')});

> meteor
...
TypeError: Property 'First' of object [object Object] is not a function
...

Does anyone have any hints?

**Comment by LuisHerranz** [comment]
Yes, don't worry. The framework is client side only. Use `if (Meteor.isClient)` or put the file in a `client` folder.
