### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by ffxsam** [worona/meteorflux#28]
The documentation says this is how you create your own dispatcher (which is also handy when using this package inside another package, when you don't want to have conflicts with the main `Dispatcher`):

    var otherDispatcher = new MeteorFlux.Dispatcher();

This is missing a couple additional steps:

    otherDispatcher.addDispatchFilter(otherDispatcher._curatePayload);
    otherDispatcher.addRegisterFilter(otherDispatcher._curateCallback);

**Comment by LuisHerranz** [comment]
Yes, if you want to be able to use the string as first parameter. I will add it, thanks.
