### ISSUE TITLE
Same action dispatched repeatedly only "fires" once

### ISSUE THREAD

**Issue by jaskinn** [worona/meteorflux#29]
I'm trying to keep track of what a user types into an input. After the first key up, an action is dispatched (LETTER_ENTERED) and everything works as expected. Then the user enters another letter and the same action is dispatched. This time nothing in 'State.set' is run and the state is not updated with the second letter.

To get it to work, I have to dispatch a dummy action before (and call Tracker.flush) the LETTER_ENTERED action

**Comment by LuisHerranz** [comment]
Could you please share the relevant code here?

**Comment by jaskinn** [comment]
Sure. To replicate I created a new project.

> meteor create entering_letters

Then I modified the generated "hello" template, by adding in a text input field:
'''
<template name="hello">
    <input type="text">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>
'''

The other modification was in Template.hello.events and I added a State.set call (all in the generated entering_letters.js) in the client scope.
'''
if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.hello.helpers({
    counter: function () {
      return Session.get('counter');
    }
  });

  Template.hello.events({
      'keyup input': function(evt, tmpl) {
          //Dispatch("dummy");
          //Tracker.flush();
          Dispatch("LETTER_ENTERED", {data: evt.target.value});
      },
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
    }
  });

  State.set("entered_letters", function(state) {
      if (state === void 0) {state = "";}
      switch(Action.type()) {
          case "LETTER_ENTERED":
            var payload = Action.payload();
            return payload.data;
          default:
            return state;
      }
  });
}
'''

With the "dummy" action commented out - type the word "letters" into the textbox. Checking the state on the browser console:

> State.get("entered_letters")
> "l"

Now uncomment the "dummy" action dispatch (and the Tracker.flush) - type the word "letters" into the textbook. Checking the state on the browser console:

> State.get("entered_letters")
> "letters"

**Comment by LuisHerranz** [comment]
Ok, it looks like if you dispatch the same Action.type() twice, it doesn't invalidate the state functions because of how Meteor reactivity works.

Thanks for the input, I will solve it asap.

**Comment by luisherranz** [comment]
This has been solved. Test here:
https://github.com/worona/meteorflux/blob/devel/packages/meteorflux/tests/client/meteorflux-tests.js#L492
