### ISSUE TITLE
Redux-like action creators with thunk middleware

### ISSUE THREAD

**Issue by jreinert** [worona/meteorflux#30]
Hello,

I'd like to see something like Redux' action creators which won't dispatch anything itself but always only return a message to be used with dispatch. So instead of just calling `myAction(foo, bar)` it'd be `Dispatcher.dispatch(myAction(foo, bar))`. This would IMHO keep the dispatch calls more transparent and allow easier testing.

The only trouble is - as always - async actions. Those are handled pretty nicely with the thunk middleware in redux. It allows to write action creators which return a function that receives a `dispatch` function. This function will be used to dispatch the actual action. The dispatch call remains the same: `dispatch(myAsyncAction(foo, bar))` so It's immediately clear that something is dispatched here.

Internally the async action creator can use other action creators which i turn can also be asynchronous. I think this is very elegant since it keeps action creator functions small and simple and therefor easy to test.

What's your take on this?

**Comment by LuisHerranz** [comment]
We don't use Redux' action creators actually, so we don't have that problem.

You can write the middleware yourself using the `addDispatchFilter` function:
https://github.com/worona/meteorflux/blob/devel/packages/dispatcher/lib/dispatcher.js#L144

Simply, you can check if the action is an object (sync) or a function (async) and proceed accordingly. If it is a function, call it with `dispatch` as parameter so the function itself can use it to dispatch when the async operation resolves.

**Comment by LuisHerranz** [comment]
You probably need a way to prevent the original dispatch from the filter. We can do so returning false instead of the payload in the filter, for example. If you want to go ahead with this make a PR and I will accept it.

**Comment by jreinert** [comment]
Very nice! I wasn't aware of that function. I'll make a PR as suggested.
