### ISSUE TITLE
AppState: week dependencies? (or separation)

### ISSUE THREAD

**Issue by mrzafod** [worona/meteorflux#36]
Hi, first thanks for this brilliant solution! Is it possible to set a **_week**_ dependency on a blaze-template-helpers package. Meteor is not the smallest one. Maybe it is more usable to carry that stuff out? Separate package for example?

**Comment by luisherranz** [comment]
You are absolutely right, Blaze is not necessary so it should be a week dependency. I think I already did that for the other MeteorFlux helpers.

Anyway, I'll do it as soon as I can, but PR's are welcomed :)

**Comment by luisherranz** [comment]
Ohh, by the way, AppState is deprecated. Please use [ReactiveState](https://github.com/worona/meteorflux/tree/devel/packages/reactive-state) instead.

**Comment by mrzafod** [comment]
thanks

**Comment by luisherranz** [comment]
`{ weak: true }` doesn't support testing, so we have moved the Blaze functionality it to a new package called Blaze Utils.

To add it use

```
meteor add meteorflux:blaze-utils
```

**Comment by mrzafod** [comment]
Oh, thanks, thats nice.
