### ISSUE TITLE
Strange difference between AppState and Session

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#4]
Consider the following code, using `kadira:flow-router` and `kadira:blaze-layout` (you can try it in [this meteorPad](http://meteorpad.com/pad/YYYnZJwbb6GpBA8Kb/Strange%20difference%20between%20AppState%20and%20Session)):
```html
<body>
</body>

<template name="myTemplate">
  <h4>Hello World</h4>
</template>
```

```javascript
Tracker.autorun(function() {
  var template = AppState.get('template');
  BlazeLayout.render(template);
})

FlowRouter.notFound = {
  action: function() {
    AppState.set('template', 'myTemplate');
  }
};
```

This code doesn't work, i.e. `myTemplate`is never rendered.
But if you replace `AppState` by `Session`, it works correctly.

**Comment by steph643** [comment]
This seems to relate to how the various packages manage their startup phases.

**Comment by LuisHerranz** [comment]
May I see your example of Session working?

Because it's not working here:
http://meteorpad.com/pad/pEBfkfmBofzMDCwf7/

It looks like the first `Blaze.layout` call won't work unless it's wrapped in a `Meteor.startup` callback.

```javascript
Meteor.startup(function(){
  Tracker.autorun(function() {
    var template = Session.get('template');
    BlazeLayout.render(template);
  });
});
```

I will keep experimenting with this anyway.

**Comment by steph643** [comment]
You are right, it doesn't wotk with Session either. Sorry for this.

**Comment by steph643** [comment]
For those landing here, the BlazeLayout issue is tracked [here](https://github.com/kadirahq/blaze-layout/issues/48).

**Comment by LuisHerranz** [comment]
No problem :)

I will close this, then.
