### ISSUE TITLE
SSR with MeteorFlux

### ISSUE THREAD

**Issue by fermuch** [worona/meteorflux#40]
I'm working with isomorphic components in react.
With SSR and ReactRouterSSR, I can pre-render the full state of the app for the user. This makes the user experience way better, since the page seems to load several times faster.

I found [this issue](https://github.com/worona/meteorflux/issues/14), which talks about the same thing, but for AppState.

> Ok, so I guess you are fine with a version of AppState which is defined on the server and only sets and gets stuff, without reactivity, for the first render. Is that ok?

As of now, `State` is undefined in the server, making it impossible to pre-render on the server. If we can get a static State, which get/sets without reactivity, it will send the first computation of the values to the client, and I think that's enough, since most of the time, when the user enters the site (loads the url), the State is static.

**Comment by luisherranz** [comment]
We have switched to React so we definitively want to work on this, but we will start probably at the end of January. If you need it before you can fork ReactiveState now and if you have any doubt about how it works I will help you out. The code is commented:
https://github.com/worona/meteorflux/blob/devel/packages/reactive-state/lib/reactive-state.js

**Comment by fermuch** [comment]
I just made MeteorFlux and ReactiveState available on the server, and all the tests are passing. I have also tested if State.{get,set,modify} works as expected on the server, and everything is working so far.

I'll create a PR with these changes.

**Comment by luisherranz** [comment]
Superb, thanks.

**Comment by luisherranz** [comment]
I am going to close this for now. You can reopen it if you find any issue.
