### ISSUE TITLE
State doesn't change to undefined

### ISSUE THREAD

**Issue by justrag** [worona/meteorflux#51]
A problem I noticed - State.modify leaves the old version of state if the new one is undefined.
I put the demonstration on fluxproblem.meteor.com and github.com/justrag/fluxproblem:
once you choose "post 1" or "post 2", you'd never get "no post found" text again when clicking "post 3" (even though there's no post with number "3" in db).

**Comment by luisherranz** [comment]
That's probably not documented, you are right. If you don't return or return `undefined` (which in JS is the same thing) state is not changed.

I'd suggest you to return `false` instead:

``` javascript
State.modify('chosenPost', (state = false) => {
        let postNumber = State.get('postNumber');
        let p = Posts.findOne({
            number: postNumber
        });
        console.debug("Should change the chosenPost state to: %o", p);
        return p || false; // <- just add this
    });
```
