### ISSUE TITLE
How to emit a 'change' event with this package

### ISSUE THREAD

**Issue by jerocosio** [worona/meteorflux#52]
Hi, I'm just starting to learn React and the Flux pattern, so far I think everything is going quite good, but I don't seem to know how to emit a change event when I change the values of a store, here is what I have:

```
//diseno-store.js
DisenosStore = {
    disenoSeleccionado: 1,
};

var cambiarDiseno = function(valor){
  DisenosStore.disenoSeleccionado = DisenosStore.disenoSeleccionado + valor;
};

Dispatcher.register(function(action){
   switch( action.type ){
       case "usuario-cambio-el-diseno":
           cambiarDiseno(action.data);
           break;
    }
    return true;
});
```

```
//paso-diseno.jsx
PasoDiseno = React.createClass({
  cambiarDiseno: function() {
    Dispatcher.dispatch( "usuario-cambio-el-diseno", { data: 1 } );
  },
  render() {
    return (
      <div className="paso-diseno">
          <div onClick={this.cambiarDiseno}>
            <p >Oli</p>
          </div>
      </div>
    );
  }
});
```

And on this component is where I want to display the actual value and change it every time it changes:

```
//layout-diseno.jsx
LayoutDiseno = React.createClass({
  getInitialState() {
    return {
      disenoSeleccionado: DisenosStore.disenoSeleccionado
    };
  },
  render() {
    return (
      <div className="layout-diseno">
        <TarjetaDiseno diseno={this.state.disenoSeleccionado }/>
        <OwlCarousel />
      </div>
    );
  }
});
```

```
//tarjeta-diseno.jsx
TarjetaDiseno = React.createClass({
  render() {
    return (
      <div className="tarjeta-diseno">
        <div><p>Que pedo perros { this.props.diseno } </p></div>
        <TarjetaBasica />
      </div>
    );
  }
});
```

**Comment by luisherranz** [comment]
If you want to emit a change event you should use some type of [event emitter](https://github.com/Olical/EventEmitter) and create your stores using it, like the people from Facebook does:
https://github.com/facebook/flux/blob/master/examples/flux-chat/js/stores/MessageStore.js#L44-L94

If you are using Meteor, you can avoid the need of an event emitter using reactive variables, like `ReactiveVar` or `ReactiveDict` and then inject them in your component using something like [react meteor data](https://react-in-meteor.readthedocs.org/en/latest/meteor-data/) or [TrackerReact](https://github.com/ultimatejs/tracker-react).
