### ISSUE TITLE
AppState feature request: option to disable logs

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#6]
A message is displayed in the console after each stage change. This is very helpful in some cases, but I would love to have an option to disable it.

**Comment by LuisHerranz** [comment]
It is disabled by default in v1.1.0. 

I am working right now with a debug package. I will upload it soon.

**Comment by LuisHerranz** [comment]
Closed as this would be solved by https://github.com/worona/meteorflux/issues/22
