### ISSUE TITLE
AppState feature request: better logs

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#7]
When doing this:
```javascript
  AppState.set('doc', {
    tentative: { docId: docId, queryParams: {} },
    actual   : null
  });
```

...I get this in the console:
```
"doc" => Object {tentative: Object, actual: null}
"doc.tentative" => Object {docId: "9c6HBqLtHLpWd6zND", queryParams: Object}
"doc.tentative.docId" => 9c6HBqLtHLpWd6zND
"doc.tentative.docId.queryParams" => Object {}
"doc.tentative.docId.queryParams.actual" => null
```

IMO, this is too verbose. Two lines would be enough, like this:
```
State change: "doc" =>
► Object {tentative: Object, actual: null}
```
and you let users open and browse the Object content in the console if they want to.
(you need two lines because you need a separate `console.log` to benefit from the browser ► feature).

**Comment by LuisHerranz** [comment]
Problem with your solution is that "doc" may contain objects which didn't change, so a new log is added for each invalidation.

`"doc.tentative.docId.queryParams"` is a bug, it should say `"doc.tentative.queryParams"`.

Anyway, update to v1.1.0 to get rid of that console log. Once I add hooks to the AppState we can have a proper debug package.

**Comment by LuisHerranz** [comment]
I will keep track of this in #6
