### ISSUE TITLE
AppState: meteorflux:dispatcher dependency?

### ISSUE THREAD

**Issue by steph643** [worona/meteorflux#9]
I don't use `meteorflux:dispatcher`. Why is it now installed with `meteorflux:appstate`?

**Comment by LuisHerranz** [comment]
Because it's needed by the new AppState.modify() function.

**Comment by steph643** [comment]
Maybe you could reopen this issue and add the "feedback-needed" label, so that people could suggest ways to remove this annoying dependency.

**Comment by LuisHerranz** [comment]
Let me think about how can I keep that package out if not needed.

**Comment by LuisHerranz** [comment]
We will solve this releasing the `ReactiveState` package.
